// Copyright (c) 2026 Matthew Winter
//
// This source code is licensed under the MIT license found in the LICENSE file
// in the root directory of this source tree.

// Code generated by go generate; DO NOT EDIT.

// Source snapshot date: 2026-07-18.
// Source URLs:
// - Amazon Bedrock model catalog: https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html
// - Ant Ling model catalog: https://api.ant-ling.com/v1/models
// - Anthropic models and pricing: https://docs.anthropic.com/en/docs/about-claude/models/overview
// - Azure OpenAI model catalog: https://learn.microsoft.com/azure/ai-services/openai/concepts/models
// - Cloudflare AI Gateway models: https://developers.cloudflare.com/ai-gateway/
// - Cloudflare Workers AI models: https://developers.cloudflare.com/workers-ai/models/
// - Fireworks Fire Pass setup: https://docs.fireworks.ai/firepass
// - Fireworks Anthropic-compatible Messages API: https://docs.fireworks.ai/api-reference/anthropic-messages
// - Google Gemini models: https://ai.google.dev/gemini-api/docs/models
// - Hugging Face Router models: https://huggingface.co/docs/inference-providers/index
// - Google Vertex AI Claude models: https://docs.cloud.google.com/vertex-ai/generative-ai/docs/partner-models/claude/use-claude
// - Google Vertex AI Llama models: https://docs.cloud.google.com/vertex-ai/generative-ai/docs/partner-models/llama/use-llama
// - MiniMax models: https://platform.minimaxi.com/document/models
// - Mistral models: https://docs.mistral.ai/getting-started/models/models_overview/
// - Moonshot AI models: https://platform.moonshot.ai/docs/pricing/chat
// - NVIDIA NIM models: https://integrate.api.nvidia.com/v1/models
// - OpenAI models and pricing: https://platform.openai.com/docs/models
// - OpenCode Zen models: https://opencode.ai/zen
// - OpenRouter models: https://openrouter.ai/models
// - Vercel AI Gateway models: https://ai-gateway.vercel.sh/v1/models
// - xAI models: https://docs.x.ai/developers/models
// - Z.ai models: https://docs.z.ai/

package sigma

var builtinEmbeddingModels = []EmbeddingModel{
	{
		ID:                ModelID("amazon.nova-2-multimodal-embeddings-v1:0"),
		Provider:          ProviderID("amazon-bedrock"),
		API:               EmbeddingAPI("bedrock-embeddings"),
		Name:              "Nova 2 Multimodal Embeddings",
		DefaultDimensions: 3072,
		MinDimensions:     256,
		MaxDimensions:     3072,
		MaxInputTokens:    8192,
		MaxBatchInputs:    1,
		CostCurrency:      "USD",
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"},
			"baseURL":             "https://bedrock-runtime.{region}.amazonaws.com",
			"headers":             map[string]string{},
			"modelFamily":         "nova",
		},
	},
	{
		ID:                ModelID("amazon.titan-embed-text-v2:0"),
		Provider:          ProviderID("amazon-bedrock"),
		API:               EmbeddingAPI("bedrock-embeddings"),
		Name:              "Titan Text Embeddings V2",
		DefaultDimensions: 1024,
		MinDimensions:     256,
		MaxDimensions:     1024,
		MaxInputTokens:    8192,
		MaxBatchInputs:    1,
		CostCurrency:      "USD",
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"},
			"baseURL":             "https://bedrock-runtime.{region}.amazonaws.com",
			"headers":             map[string]string{},
			"modelFamily":         "titan",
		},
	},
	{
		ID:                ModelID("cohere.embed-english-v3"),
		Provider:          ProviderID("amazon-bedrock"),
		API:               EmbeddingAPI("bedrock-embeddings"),
		Name:              "Cohere Embed English V3",
		DefaultDimensions: 1024,
		MinDimensions:     1024,
		MaxDimensions:     1024,
		MaxInputTokens:    512,
		MaxBatchInputs:    96,
		CostCurrency:      "USD",
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"},
			"baseURL":             "https://bedrock-runtime.{region}.amazonaws.com",
			"headers":             map[string]string{},
			"modelFamily":         "cohere",
		},
	},
	{
		ID:                ModelID("text-embedding-004"),
		Provider:          ProviderID("google"),
		API:               EmbeddingAPI("google-embeddings"),
		Name:              "Text Embedding 004",
		DefaultDimensions: 768,
		MinDimensions:     1,
		MaxDimensions:     768,
		MaxInputTokens:    2048,
		MaxBatchInputs:    100,
		CostCurrency:      "USD",
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"GOOGLE_API_KEY", "GOOGLE_CLOUD_API_KEY"},
			"baseURL":             "https://generativelanguage.googleapis.com/v1beta",
			"headers":             map[string]string{},
			"modelFamily":         "gemini-embedding",
		},
	},
	{
		ID:                ModelID("text-embedding-004"),
		Provider:          ProviderID("google-vertex"),
		API:               EmbeddingAPI("google-vertex-embeddings"),
		Name:              "Text Embedding 004 (Vertex)",
		DefaultDimensions: 768,
		MinDimensions:     1,
		MaxDimensions:     768,
		MaxInputTokens:    2048,
		MaxBatchInputs:    250,
		CostCurrency:      "USD",
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"GOOGLE_CLOUD_API_KEY", "GOOGLE_API_KEY"},
			"baseURL":             "https://{location}-aiplatform.googleapis.com/v1",
			"headers":             map[string]string{},
			"modelFamily":         "gemini-embedding",
			"vertexPublisher":     "google",
		},
	},
	{
		ID:                ModelID("nvidia/nv-embedqa-e5-v5"),
		Provider:          ProviderID("nvidia"),
		API:               EmbeddingAPI("openai-embeddings"),
		Name:              "NV EmbedQA E5 v5",
		DefaultDimensions: 1024,
		MinDimensions:     1024,
		MaxDimensions:     1024,
		MaxInputTokens:    8192,
		MaxBatchInputs:    100,
		CostCurrency:      "USD",
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"NVIDIA_API_KEY"},
			"baseURL":             "https://integrate.api.nvidia.com/v1",
			"headers":             map[string]string{"NVCF-POLL-SECONDS": "3600"},
			"modelFamily":         "nvidia-embedding",
		},
	},
	{
		ID:                  ModelID("text-embedding-3-large"),
		Provider:            ProviderID("openai"),
		API:                 EmbeddingAPI("openai-embeddings"),
		Name:                "Text Embedding 3 Large",
		DefaultDimensions:   3072,
		MinDimensions:       1,
		MaxDimensions:       3072,
		MaxInputTokens:      8192,
		MaxBatchInputs:      2048,
		InputCostPerMillion: 0.13,
		CostCurrency:        "USD",
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"OPENAI_API_KEY"},
			"baseURL":             "https://api.openai.com/v1",
			"headers":             map[string]string{},
			"modelFamily":         "text-embedding-3",
		},
	},
	{
		ID:                  ModelID("text-embedding-3-small"),
		Provider:            ProviderID("openai"),
		API:                 EmbeddingAPI("openai-embeddings"),
		Name:                "Text Embedding 3 Small",
		DefaultDimensions:   1536,
		MinDimensions:       1,
		MaxDimensions:       1536,
		MaxInputTokens:      8192,
		MaxBatchInputs:      2048,
		InputCostPerMillion: 0.02,
		CostCurrency:        "USD",
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"OPENAI_API_KEY"},
			"baseURL":             "https://api.openai.com/v1",
			"headers":             map[string]string{},
			"modelFamily":         "text-embedding-3",
		},
	},
}

func registerBuiltinEmbeddingModels(registry *Registry) error {
	for _, model := range builtinEmbeddingModels {
		if err := registry.RegisterEmbeddingModel(model, WithMetadataOnly()); err != nil {
			return err
		}
	}
	return nil
}
