// Copyright (c) 2026 Matthew Winter
//
// This source code is licensed under the MIT license found in the LICENSE file
// in the root directory of this source tree.

// Code generated by go generate; DO NOT EDIT.

// Source snapshot date: 2026-05-30.
// Source URLs:
// - Amazon Bedrock model catalog: https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html
// - Anthropic models and pricing: https://docs.anthropic.com/en/docs/about-claude/models/overview
// - Fireworks Fire Pass setup: https://docs.fireworks.ai/firepass
// - Google Gemini models: https://ai.google.dev/gemini-api/docs/models
// - Mistral models: https://docs.mistral.ai/getting-started/models/models_overview/
// - OpenAI models and pricing: https://platform.openai.com/docs/models
// - OpenCode Zen models: https://opencode.ai/zen
// - OpenRouter models: https://openrouter.ai/models
// - xAI models: https://docs.x.ai/developers/models

package sigma

var builtinImageModels = []ImageModel{
	{
		ID:               ModelID("gpt-image-1"),
		Provider:         ProviderID("openai"),
		API:              ImageAPI("openai-images"),
		Name:             "GPT Image 1",
		MaxWidth:         1536,
		MaxHeight:        1536,
		SupportedSizes:   []string{"1024x1024", "1024x1536", "1536x1024"},
		SupportedFormats: []string{"image/png", "image/jpeg", "image/webp"},
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"OPENAI_API_KEY"},
			"baseURL":             "https://api.openai.com/v1",
			"cost":                map[string]any{"currency": "USD", "unit": "image", "values": map[string]float64{"high": 0.167, "low": 0.011, "medium": 0.042}},
			"headers":             map[string]string{},
			"modelFamily":         "gpt-image",
		},
	},
	{
		ID:               ModelID("google/gemini-2.5-flash-image-preview"),
		Provider:         ProviderID("openrouter"),
		API:              ImageAPI("openrouter-images"),
		Name:             "Gemini 2.5 Flash Image Preview via OpenRouter",
		MaxWidth:         1024,
		MaxHeight:        1024,
		SupportedSizes:   []string{"1024x1024"},
		SupportedFormats: []string{"image/png"},
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"OPENROUTER_API_KEY"},
			"baseURL":             "https://openrouter.ai/api/v1",
			"cost":                map[string]any{"currency": "USD", "unit": "image", "values": map[string]float64{"image": 0.039}},
			"headers":             map[string]string{"HTTP-Referer": "", "X-Title": ""},
			"modelFamily":         "gemini",
			"routedProvider":      "google",
		},
	},
	{
		ID:               ModelID("x-ai/grok-imagine-image-quality"),
		Provider:         ProviderID("openrouter"),
		API:              ImageAPI("openrouter-images"),
		Name:             "xAI Grok Imagine Image Quality via OpenRouter",
		MaxWidth:         1024,
		MaxHeight:        1024,
		SupportedSizes:   []string{"1024x1024"},
		SupportedFormats: []string{"image/png"},
		ProviderMetadata: map[string]any{
			MetadataAPIKeyEnvVars: []string{"OPENROUTER_API_KEY"},
			"baseURL":             "https://openrouter.ai/api/v1",
			"cost":                map[string]any{"currency": "USD", "unit": "image", "values": map[string]float64{"image": 0}},
			"headers":             map[string]string{"HTTP-Referer": "", "X-Title": ""},
			"modelFamily":         "grok",
			"routedProvider":      "xai",
		},
	},
}

func registerBuiltinImageModels(registry *Registry) error {
	for _, model := range builtinImageModels {
		if err := registry.RegisterImageModel(model, WithMetadataOnly()); err != nil {
			return err
		}
	}
	return nil
}
