// Copyright (c) 2026 Matthew Winter
//
// This source code is licensed under the MIT license found in the LICENSE file
// in the root directory of this source tree.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"reflect"
	"sort"
	"strconv"
	"strings"

	"github.com/wintermi/sigma/internal/modeldata"
)

const generatedHeader = `// Copyright (c) 2026 Matthew Winter
//
// This source code is licensed under the MIT license found in the LICENSE file
// in the root directory of this source tree.

// Code generated by go generate; DO NOT EDIT.

`

func main() {
	if err := runGenerateModels(os.Args[1:], os.Stdout, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, "sigma-generate-models: "+strings.TrimSuffix(err.Error(), "\n"))
		os.Exit(1)
	}
}

func runGenerateModels(args []string, stdout io.Writer, stderr io.Writer) error {
	var inputPath string
	var modelsPath string
	var imageModelsPath string
	var embeddingModelsPath string
	var diffCatalogPath string
	var refreshCatalogPath string
	var modelsDevSource string
	var refreshSnapshotDate string
	var allowNetwork bool
	var report bool
	var validateNVIDIALive bool

	flags := flag.NewFlagSet("sigma-generate-models", flag.ContinueOnError)
	flags.SetOutput(stderr)
	flags.StringVar(&inputPath, "input", "internal/modeldata/catalog.json", "model metadata catalog JSON")
	flags.StringVar(&modelsPath, "models", "models_generated.go", "generated text model Go file")
	flags.StringVar(&imageModelsPath, "image-models", "image_models_generated.go", "generated image model Go file")
	flags.StringVar(&embeddingModelsPath, "embedding-models", "embedding_models_generated.go", "generated embedding model Go file")
	flags.StringVar(&diffCatalogPath, "diff-catalog", "", "validated candidate catalog JSON to compare without generating files")
	flags.StringVar(&refreshCatalogPath, "refresh-catalog", "", "write a validated candidate catalog JSON without generating Go files")
	flags.StringVar(&modelsDevSource, "models-dev-source", "https://models.dev/api.json", "models.dev API snapshot path or URL for -refresh-catalog")
	flags.StringVar(&refreshSnapshotDate, "refresh-snapshot-date", "", "snapshot date for -refresh-catalog candidate output, in YYYY-MM-DD format")
	flags.BoolVar(&allowNetwork, "allow-network", false, "allow HTTP(S) catalog source reads for refresh modes")
	flags.BoolVar(&report, "report", false, "print a deterministic catalog summary")
	flags.BoolVar(&validateNVIDIALive, "validate-nvidia-live", false, "fetch NVIDIA NIM /models and report direct text catalog drift")
	if err := flags.Parse(args); err != nil {
		return fmt.Errorf("parse flags: %w", err)
	}

	catalog, err := modeldata.Load(inputPath)
	if err != nil {
		return fmt.Errorf("load catalog: %w", err)
	}
	if diffCatalogPath != "" {
		candidate, err := modeldata.Load(diffCatalogPath)
		if err != nil {
			return fmt.Errorf("load diff catalog: %w", err)
		}
		if _, err := fmt.Fprint(stdout, renderCatalogDiff(catalog, candidate)); err != nil {
			return fmt.Errorf("write catalog diff: %w", err)
		}
		return nil
	}
	if refreshCatalogPath != "" {
		candidate, err := buildModelsDevCandidateCatalog(catalog, modelsDevSource, refreshSnapshotDate, allowNetwork)
		if err != nil {
			return fmt.Errorf("refresh catalog: %w", err)
		}
		if err := modeldata.Write(refreshCatalogPath, candidate); err != nil {
			return fmt.Errorf("write refresh catalog: %w", err)
		}
		return nil
	}
	if validateNVIDIALive {
		output, err := renderNVIDIALiveValidation(catalog, true, fetchNVIDIALiveModelIDs)
		if err != nil {
			return fmt.Errorf("validate nvidia live catalog: %w", err)
		}
		if _, err := fmt.Fprint(stderr, output); err != nil {
			return fmt.Errorf("write nvidia live validation: %w", err)
		}
	}
	if err := writeGoFile(modelsPath, renderTextModels(catalog)); err != nil {
		return fmt.Errorf("write text models: %w", err)
	}
	if err := writeGoFile(imageModelsPath, renderImageModels(catalog)); err != nil {
		return fmt.Errorf("write image models: %w", err)
	}
	if err := writeGoFile(embeddingModelsPath, renderEmbeddingModels(catalog)); err != nil {
		return fmt.Errorf("write embedding models: %w", err)
	}
	if report {
		if _, err := fmt.Fprint(stdout, renderCatalogReport(catalog)); err != nil {
			return fmt.Errorf("write catalog report: %w", err)
		}
	}
	return nil
}

func renderTextModels(catalog modeldata.Catalog) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	writeSnapshotComment(&b, catalog)
	b.WriteString("package sigma\n\n")
	b.WriteString("var builtinTextModels = []Model{\n")
	for _, model := range catalog.TextModels {
		writeTextModel(&b, model)
	}
	b.WriteString("}\n\n")
	b.WriteString("func registerBuiltinTextModels(registry *Registry) error {\n")
	b.WriteString("\tfor _, model := range builtinTextModels {\n")
	b.WriteString("\t\tif err := registry.RegisterModel(model, WithMetadataOnly()); err != nil {\n")
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func generatedBoolPtr(value bool) *bool {\n")
	b.WriteString("\treturn &value\n")
	b.WriteString("}\n")
	return b.Bytes()
}

func renderImageModels(catalog modeldata.Catalog) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	writeSnapshotComment(&b, catalog)
	b.WriteString("package sigma\n\n")
	b.WriteString("var builtinImageModels = []ImageModel{\n")
	for _, model := range catalog.ImageModels {
		writeImageModel(&b, model)
	}
	b.WriteString("}\n\n")
	b.WriteString("func registerBuiltinImageModels(registry *Registry) error {\n")
	b.WriteString("\tfor _, model := range builtinImageModels {\n")
	b.WriteString("\t\tif err := registry.RegisterImageModel(model, WithMetadataOnly()); err != nil {\n")
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")
	return b.Bytes()
}

func renderEmbeddingModels(catalog modeldata.Catalog) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	writeSnapshotComment(&b, catalog)
	b.WriteString("package sigma\n\n")
	b.WriteString("var builtinEmbeddingModels = []EmbeddingModel{\n")
	for _, model := range catalog.EmbeddingModels {
		writeEmbeddingModel(&b, model)
	}
	b.WriteString("}\n\n")
	b.WriteString("func registerBuiltinEmbeddingModels(registry *Registry) error {\n")
	b.WriteString("\tfor _, model := range builtinEmbeddingModels {\n")
	b.WriteString("\t\tif err := registry.RegisterEmbeddingModel(model, WithMetadataOnly()); err != nil {\n")
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")
	return b.Bytes()
}

type catalogReportBucket struct {
	Provider string
	API      string
	Count    int
}

type catalogDiffRow struct {
	Key    string
	Fields []string
}

type catalogDiffSection struct {
	Title     string
	Added     []string
	Removed   []string
	Changed   []catalogDiffRow
	Unchanged int
}

func renderCatalogReport(catalog modeldata.Catalog) string {
	var b strings.Builder
	fmt.Fprintf(&b, "Catalog snapshot: %s\n", catalog.SnapshotDate)
	fmt.Fprintf(&b, "Sources: %d\n", len(catalog.Sources))
	writeTextCatalogReport(&b, catalog.TextModels)
	writeCatalogReportSection(&b, "Image models", imageCatalogBuckets(catalog.ImageModels))
	writeCatalogReportSection(&b, "Embedding models", embeddingCatalogBuckets(catalog.EmbeddingModels))
	return b.String()
}

func renderCatalogDiff(base, candidate modeldata.Catalog) string {
	sections := []catalogDiffSection{
		diffCatalogRows(
			"Text models",
			base.TextModels,
			candidate.TextModels,
			textCatalogDiffKey,
			textCatalogChangedFields,
		),
		diffCatalogRows(
			"Image models",
			base.ImageModels,
			candidate.ImageModels,
			imageCatalogDiffKey,
			imageCatalogChangedFields,
		),
		diffCatalogRows(
			"Embedding models",
			base.EmbeddingModels,
			candidate.EmbeddingModels,
			embeddingCatalogDiffKey,
			embeddingCatalogChangedFields,
		),
	}

	var b strings.Builder
	fmt.Fprintf(&b, "Catalog diff: %s -> %s\n", base.SnapshotDate, candidate.SnapshotDate)
	for _, section := range sections {
		writeCatalogDiffSection(&b, section)
	}
	return b.String()
}

func diffCatalogRows[T any](
	title string,
	baseRows []T,
	candidateRows []T,
	key func(T) string,
	changedFields func(T, T) []string,
) catalogDiffSection {
	baseByKey := make(map[string]T, len(baseRows))
	candidateByKey := make(map[string]T, len(candidateRows))
	for _, row := range baseRows {
		baseByKey[key(row)] = row
	}
	for _, row := range candidateRows {
		candidateByKey[key(row)] = row
	}

	section := catalogDiffSection{Title: title}
	for _, rowKey := range sortedMapKeys(candidateByKey) {
		candidateRow := candidateByKey[rowKey]
		baseRow, ok := baseByKey[rowKey]
		if !ok {
			section.Added = append(section.Added, rowKey)
			continue
		}
		fields := changedFields(baseRow, candidateRow)
		if len(fields) == 0 {
			section.Unchanged++
			continue
		}
		section.Changed = append(section.Changed, catalogDiffRow{Key: rowKey, Fields: fields})
	}
	for _, rowKey := range sortedMapKeys(baseByKey) {
		if _, ok := candidateByKey[rowKey]; !ok {
			section.Removed = append(section.Removed, rowKey)
		}
	}
	return section
}

func writeCatalogDiffSection(b *strings.Builder, section catalogDiffSection) {
	fmt.Fprintf(
		b,
		"%s: added %d, removed %d, changed %d, unchanged %d\n",
		section.Title,
		len(section.Added),
		len(section.Removed),
		len(section.Changed),
		section.Unchanged,
	)
	writeCatalogDiffKeyList(b, "Added", "+", section.Added)
	writeCatalogDiffKeyList(b, "Removed", "-", section.Removed)
	if len(section.Changed) == 0 {
		return
	}
	b.WriteString("  Changed:\n")
	for _, row := range section.Changed {
		fmt.Fprintf(b, "    ~ %s: %s\n", row.Key, strings.Join(row.Fields, ", "))
	}
}

func writeCatalogDiffKeyList(b *strings.Builder, title, marker string, keys []string) {
	if len(keys) == 0 {
		return
	}
	fmt.Fprintf(b, "  %s:\n", title)
	for _, key := range keys {
		fmt.Fprintf(b, "    %s %s\n", marker, key)
	}
}

func textCatalogDiffKey(model modeldata.TextModel) string {
	return catalogDiffKey(model.Provider, model.API, model.ID)
}

func imageCatalogDiffKey(model modeldata.ImageModel) string {
	return catalogDiffKey(model.Provider, model.API, model.ID)
}

func embeddingCatalogDiffKey(model modeldata.EmbeddingModel) string {
	return catalogDiffKey(model.Provider, model.API, model.ID)
}

func catalogDiffKey(provider, api, id string) string {
	return provider + " / " + api + " / " + id
}

func textCatalogChangedFields(base, candidate modeldata.TextModel) []string {
	var fields []string
	appendChangedField(&fields, "name", base.Name, candidate.Name)
	appendChangedField(&fields, "baseURL", base.BaseURL, candidate.BaseURL)
	appendChangedField(&fields, "supportedInputs", base.SupportedInputs, candidate.SupportedInputs)
	appendChangedField(&fields, "supportsTools", base.SupportsTools, candidate.SupportsTools)
	appendChangedField(&fields, "supportsThinking", base.SupportsThinking, candidate.SupportsThinking)
	appendChangedField(&fields, "thinkingLevels", base.ThinkingLevels, candidate.ThinkingLevels)
	appendChangedField(&fields, "thinkingLevelMap", base.ThinkingLevelMap, candidate.ThinkingLevelMap)
	appendChangedField(&fields, "unsupportedThinkingLevels", base.UnsupportedThinkingLevels, candidate.UnsupportedThinkingLevels)
	appendChangedField(&fields, "cost", base.Cost, candidate.Cost)
	appendChangedField(&fields, "contextWindow", base.ContextWindow, candidate.ContextWindow)
	appendChangedField(&fields, "maxOutputTokens", base.MaxOutputTokens, candidate.MaxOutputTokens)
	appendChangedField(&fields, "headers", base.Headers, candidate.Headers)
	appendChangedField(&fields, "authEnvNames", base.AuthEnvNames, candidate.AuthEnvNames)
	appendChangedField(&fields, "defaultTransport", base.DefaultTransport, candidate.DefaultTransport)
	appendChangedField(&fields, "openAICompletionsCompat", base.OpenAICompletionsCompat, candidate.OpenAICompletionsCompat)
	appendChangedField(&fields, "anthropicMessagesCompat", base.AnthropicMessagesCompat, candidate.AnthropicMessagesCompat)
	appendChangedField(&fields, "openAIResponsesCompat", base.OpenAIResponsesCompat, candidate.OpenAIResponsesCompat)
	appendChangedField(&fields, "azureOpenAIResponses", base.AzureOpenAIResponses, candidate.AzureOpenAIResponses)
	appendChangedField(&fields, "openAICodexResponses", base.OpenAICodexResponses, candidate.OpenAICodexResponses)
	appendChangedField(&fields, "providerMetadata", base.ProviderMetadata, candidate.ProviderMetadata)
	return fields
}

func imageCatalogChangedFields(base, candidate modeldata.ImageModel) []string {
	var fields []string
	appendChangedField(&fields, "name", base.Name, candidate.Name)
	appendChangedField(&fields, "baseURL", base.BaseURL, candidate.BaseURL)
	appendChangedField(&fields, "maxWidth", base.MaxWidth, candidate.MaxWidth)
	appendChangedField(&fields, "maxHeight", base.MaxHeight, candidate.MaxHeight)
	appendChangedField(&fields, "supportedSizes", base.SupportedSizes, candidate.SupportedSizes)
	appendChangedField(&fields, "supportedFormats", base.SupportedFormats, candidate.SupportedFormats)
	appendChangedField(&fields, "cost", base.Cost, candidate.Cost)
	appendChangedField(&fields, "headers", base.Headers, candidate.Headers)
	appendChangedField(&fields, "authEnvNames", base.AuthEnvNames, candidate.AuthEnvNames)
	appendChangedField(&fields, "providerMetadata", base.ProviderMetadata, candidate.ProviderMetadata)
	return fields
}

func embeddingCatalogChangedFields(base, candidate modeldata.EmbeddingModel) []string {
	var fields []string
	appendChangedField(&fields, "name", base.Name, candidate.Name)
	appendChangedField(&fields, "baseURL", base.BaseURL, candidate.BaseURL)
	appendChangedField(&fields, "defaultDimensions", base.DefaultDimensions, candidate.DefaultDimensions)
	appendChangedField(&fields, "minDimensions", base.MinDimensions, candidate.MinDimensions)
	appendChangedField(&fields, "maxDimensions", base.MaxDimensions, candidate.MaxDimensions)
	appendChangedField(&fields, "maxInputTokens", base.MaxInputTokens, candidate.MaxInputTokens)
	appendChangedField(&fields, "maxBatchInputs", base.MaxBatchInputs, candidate.MaxBatchInputs)
	appendChangedField(&fields, "maxBatchBytes", base.MaxBatchBytes, candidate.MaxBatchBytes)
	appendChangedField(&fields, "inputCostPerMillion", base.InputCostPerMillion, candidate.InputCostPerMillion)
	appendChangedField(&fields, "currency", base.Currency, candidate.Currency)
	appendChangedField(&fields, "headers", base.Headers, candidate.Headers)
	appendChangedField(&fields, "authEnvNames", base.AuthEnvNames, candidate.AuthEnvNames)
	appendChangedField(&fields, "providerMetadata", base.ProviderMetadata, candidate.ProviderMetadata)
	return fields
}

func appendChangedField(fields *[]string, name string, base, candidate any) {
	if !reflect.DeepEqual(base, candidate) {
		*fields = append(*fields, name)
	}
}

func writeTextCatalogReport(b *strings.Builder, models []modeldata.TextModel) {
	toolCapable := 0
	reasoningCapable := 0
	for _, model := range models {
		if model.SupportsTools {
			toolCapable++
		}
		if model.SupportsThinking || len(model.ThinkingLevels) > 0 || len(model.ThinkingLevelMap) > 0 {
			reasoningCapable++
		}
	}
	fmt.Fprintf(b, "Text models: %d (tools: %d, reasoning: %d)\n", len(models), toolCapable, reasoningCapable)
	writeCatalogReportBuckets(b, textCatalogBuckets(models))
}

func writeCatalogReportSection(b *strings.Builder, title string, buckets []catalogReportBucket) {
	total := 0
	for _, bucket := range buckets {
		total += bucket.Count
	}
	fmt.Fprintf(b, "%s: %d\n", title, total)
	writeCatalogReportBuckets(b, buckets)
}

func writeCatalogReportBuckets(b *strings.Builder, buckets []catalogReportBucket) {
	for _, bucket := range buckets {
		fmt.Fprintf(b, "  %s / %s: %d\n", bucket.Provider, bucket.API, bucket.Count)
	}
}

func textCatalogBuckets(models []modeldata.TextModel) []catalogReportBucket {
	counts := make(map[string]int)
	for _, model := range models {
		counts[catalogReportKey(model.Provider, model.API)]++
	}
	return sortedCatalogReportBuckets(counts)
}

func imageCatalogBuckets(models []modeldata.ImageModel) []catalogReportBucket {
	counts := make(map[string]int)
	for _, model := range models {
		counts[catalogReportKey(model.Provider, model.API)]++
	}
	return sortedCatalogReportBuckets(counts)
}

func embeddingCatalogBuckets(models []modeldata.EmbeddingModel) []catalogReportBucket {
	counts := make(map[string]int)
	for _, model := range models {
		counts[catalogReportKey(model.Provider, model.API)]++
	}
	return sortedCatalogReportBuckets(counts)
}

func sortedCatalogReportBuckets(counts map[string]int) []catalogReportBucket {
	keys := sortedMapKeys(counts)
	buckets := make([]catalogReportBucket, 0, len(keys))
	for _, key := range keys {
		provider, api, _ := strings.Cut(key, "\x00")
		buckets = append(buckets, catalogReportBucket{
			Provider: provider,
			API:      api,
			Count:    counts[key],
		})
	}
	return buckets
}

func catalogReportKey(provider, api string) string {
	return provider + "\x00" + api
}

func writeSnapshotComment(b *bytes.Buffer, catalog modeldata.Catalog) {
	fmt.Fprintf(b, "// Source snapshot date: %s.\n", catalog.SnapshotDate)
	b.WriteString("// Source URLs:\n")
	for _, source := range catalog.Sources {
		fmt.Fprintf(b, "// - %s: %s\n", source.Name, source.URL)
	}
	b.WriteByte('\n')
}

func writeTextModel(b *bytes.Buffer, model modeldata.TextModel) {
	b.WriteString("\t{\n")
	writeStringField(b, "ID", "ModelID", model.ID)
	writeStringField(b, "Provider", "ProviderID", model.Provider)
	writeStringField(b, "API", "API", model.API)
	writeStringField(b, "Name", "", model.Name)
	writeIntField(b, "ContextWindow", model.ContextWindow)
	writeIntField(b, "MaxOutputTokens", model.MaxOutputTokens)
	writeStringSliceField(b, "SupportedInputs", "ContentBlockType", model.SupportedInputs)
	writeBoolField(b, "SupportsTools", model.SupportsTools)
	writeBoolField(b, "SupportsThinking", model.SupportsThinking)
	writeStringSliceField(b, "ThinkingLevels", "ThinkingLevel", model.ThinkingLevels)
	writeThinkingLevelMapField(b, model.ThinkingLevelMap)
	writeStringSliceField(b, "UnsupportedThinkingLevels", "ThinkingLevel", model.UnsupportedThinkingLevels)
	writeFloatField(b, "InputCostPerMillion", model.Cost.InputPerMillion)
	writeFloatField(b, "OutputCostPerMillion", model.Cost.OutputPerMillion)
	writeFloatField(b, "CacheReadInputCostPerMillion", model.Cost.CacheReadInputPerMillion)
	writeFloatField(b, "CacheWriteInputCostPerMillion", model.Cost.CacheWriteInputPerMillion)
	writeCostTiers(b, model.Cost.Tiers)
	writeStringField(b, "CostCurrency", "", model.Cost.Currency)
	writeStringField(b, "DefaultTransport", "Transport", model.DefaultTransport)
	writeOpenAICompatField(b, model.OpenAICompletionsCompat)
	writeAnthropicCompatField(b, model.AnthropicMessagesCompat)
	writeOpenAIResponsesCompatField(b, model.OpenAIResponsesCompat)
	writeAzureField(b, model.AzureOpenAIResponses)
	writeCodexField(b, model.OpenAICodexResponses)
	writeProviderMetadataField(b, textProviderMetadata(model))
	b.WriteString("\t},\n")
}

func writeImageModel(b *bytes.Buffer, model modeldata.ImageModel) {
	b.WriteString("\t{\n")
	writeStringField(b, "ID", "ModelID", model.ID)
	writeStringField(b, "Provider", "ProviderID", model.Provider)
	writeStringField(b, "API", "ImageAPI", model.API)
	writeStringField(b, "Name", "", model.Name)
	writeIntField(b, "MaxWidth", model.MaxWidth)
	writeIntField(b, "MaxHeight", model.MaxHeight)
	writeStringSliceField(b, "SupportedSizes", "", model.SupportedSizes)
	writeStringSliceField(b, "SupportedFormats", "", model.SupportedFormats)
	writeProviderMetadataField(b, imageProviderMetadata(model))
	b.WriteString("\t},\n")
}

func writeEmbeddingModel(b *bytes.Buffer, model modeldata.EmbeddingModel) {
	b.WriteString("\t{\n")
	writeStringField(b, "ID", "ModelID", model.ID)
	writeStringField(b, "Provider", "ProviderID", model.Provider)
	writeStringField(b, "API", "EmbeddingAPI", model.API)
	writeStringField(b, "Name", "", model.Name)
	writeIntField(b, "DefaultDimensions", model.DefaultDimensions)
	writeIntField(b, "MinDimensions", model.MinDimensions)
	writeIntField(b, "MaxDimensions", model.MaxDimensions)
	writeIntField(b, "MaxInputTokens", model.MaxInputTokens)
	writeIntField(b, "MaxBatchInputs", model.MaxBatchInputs)
	writeIntField(b, "MaxBatchBytes", model.MaxBatchBytes)
	writeFloatField(b, "InputCostPerMillion", model.InputCostPerMillion)
	writeStringField(b, "CostCurrency", "", model.Currency)
	writeProviderMetadataField(b, embeddingProviderMetadata(model))
	b.WriteString("\t},\n")
}

func textProviderMetadata(model modeldata.TextModel) map[string]any {
	metadata := cloneAnyMap(model.ProviderMetadata)
	metadata["baseURL"] = model.BaseURL
	metadata["headers"] = cloneStringMap(model.Headers)
	metadata["apiKeyEnvVars"] = append([]string(nil), model.AuthEnvNames...)
	return metadata
}

func imageProviderMetadata(model modeldata.ImageModel) map[string]any {
	metadata := cloneAnyMap(model.ProviderMetadata)
	metadata["baseURL"] = model.BaseURL
	metadata["headers"] = cloneStringMap(model.Headers)
	metadata["apiKeyEnvVars"] = append([]string(nil), model.AuthEnvNames...)
	metadata["cost"] = map[string]any{
		"unit":     model.Cost.Unit,
		"currency": model.Cost.Currency,
		"values":   cloneFloatMap(model.Cost.Values),
	}
	return metadata
}

func embeddingProviderMetadata(model modeldata.EmbeddingModel) map[string]any {
	metadata := cloneAnyMap(model.ProviderMetadata)
	metadata["baseURL"] = model.BaseURL
	metadata["headers"] = cloneStringMap(model.Headers)
	metadata["apiKeyEnvVars"] = append([]string(nil), model.AuthEnvNames...)
	return metadata
}

func writeOpenAICompatField(b *bytes.Buffer, compat *modeldata.OpenAICompletionsCompat) {
	if compat == nil {
		return
	}
	b.WriteString("\t\tOpenAICompletionsCompat: &OpenAICompletionsCompat{\n")
	writeStringField(b, "SupportsStore", "OpenAICompatSupport", compat.SupportsStore)
	writeStringField(b, "SupportsDeveloperRole", "OpenAICompatSupport", compat.SupportsDeveloperRole)
	writeStringField(b, "ReasoningFormat", "OpenAICompletionsReasoningFormat", compat.ReasoningFormat)
	writeStringField(b, "SupportsReasoningEffort", "OpenAICompatSupport", compat.SupportsReasoningEffort)
	writeStringField(b, "SupportsStreamingUsage", "OpenAICompatSupport", compat.SupportsStreamingUsage)
	writeStringField(b, "SupportsStrictTools", "OpenAICompatSupport", compat.SupportsStrictTools)
	writeStringField(b, "SupportsRequiredToolChoice", "OpenAICompatSupport", compat.SupportsRequiredToolChoice)
	writeStringField(b, "SupportsToolStream", "OpenAICompatSupport", compat.SupportsToolStream)
	writeStringField(b, "SupportsJSONSchemaResponseFormat", "OpenAICompatSupport", compat.SupportsJSONSchemaResponseFormat)
	writeStringField(b, "MaxTokensField", "OpenAICompletionsMaxTokensField", compat.MaxTokensField)
	writeStringField(b, "CacheControlFormat", "OpenAICompletionsCacheControlFormat", compat.CacheControlFormat)
	writeStringField(b, "SupportsSessionAffinity", "OpenAICompatSupport", compat.SupportsSessionAffinity)
	writeStringField(b, "RequiresToolResultName", "OpenAICompatSupport", compat.RequiresToolResultName)
	writeStringField(b, "RequiresAssistantAfterToolResult", "OpenAICompatSupport", compat.RequiresAssistantAfterToolResult)
	writeStringField(b, "RequiresToolsForToolHistory", "OpenAICompatSupport", compat.RequiresToolsForToolHistory)
	writeStringField(b, "RequiresReasoningContentOnAssistantMessages", "OpenAICompatSupport", compat.RequiresReasoningContentOnAssistantMessages)
	writeOpenRouterRoutingField(b, compat.OpenRouterRouting)
	writeVercelRoutingField(b, compat.VercelAIGatewayRouting)
	b.WriteString("\t\t},\n")
}

func writeAnthropicCompatField(b *bytes.Buffer, compat *modeldata.AnthropicMessagesCompat) {
	if compat == nil {
		return
	}
	b.WriteString("\t\tAnthropicMessagesCompat: &AnthropicMessagesCompat{\n")
	writeStringField(b, "SupportsEagerToolInputStreaming", "AnthropicCompatSupport", compat.SupportsEagerToolInputStreaming)
	writeStringField(b, "SupportsLongCacheRetention", "AnthropicCompatSupport", compat.SupportsLongCacheRetention)
	writeStringField(b, "SupportsSessionAffinity", "AnthropicCompatSupport", compat.SupportsSessionAffinity)
	writeStringField(b, "SupportsCacheControlOnTools", "AnthropicCompatSupport", compat.SupportsCacheControlOnTools)
	writeStringField(b, "SupportsEmptyThinkingSignature", "AnthropicCompatSupport", compat.SupportsEmptyThinkingSignature)
	writeStringField(b, "SupportsTemperature", "AnthropicCompatSupport", compat.SupportsTemperature)
	writeStringField(b, "SupportsDisabledThinking", "AnthropicCompatSupport", compat.SupportsDisabledThinking)
	writeStringField(b, "SupportsToolReferences", "AnthropicCompatSupport", compat.SupportsToolReferences)
	writeStringField(b, "ThinkingFormat", "AnthropicThinkingFormat", compat.ThinkingFormat)
	b.WriteString("\t\t},\n")
}

func writeOpenAIResponsesCompatField(b *bytes.Buffer, compat *modeldata.OpenAIResponsesCompat) {
	if compat == nil {
		return
	}
	b.WriteString("\t\tOpenAIResponsesCompat: &OpenAIResponsesCompat{\n")
	writeBoolField(b, "SupportsToolSearch", compat.SupportsToolSearch)
	writeStringField(b, "SessionAffinityFormat", "OpenAIResponsesSessionAffinityFormat", compat.SessionAffinityFormat)
	b.WriteString("\t\t},\n")
}

func writeOpenRouterRoutingField(b *bytes.Buffer, routing *modeldata.OpenRouterRoutingPreference) {
	if routing == nil {
		return
	}
	b.WriteString("\t\t\tOpenRouterRouting: &OpenRouterRoutingPreference{\n")
	writeStringSliceField(b, "Order", "", routing.Order)
	writeStringSliceField(b, "Only", "", routing.Only)
	writeStringSliceField(b, "Ignore", "", routing.Ignore)
	writeBoolPtrField(b, "AllowFallbacks", routing.AllowFallbacks)
	writeBoolPtrField(b, "RequireParameters", routing.RequireParameters)
	writeStringField(b, "DataCollection", "", routing.DataCollection)
	writeBoolPtrField(b, "ZDR", routing.ZDR)
	writeBoolPtrField(b, "EnforceDistillableText", routing.EnforceDistillableText)
	writeStringSliceField(b, "Quantizations", "", routing.Quantizations)
	writeAnyMapField(b, "MaxPrice", routing.MaxPrice)
	writeAnyField(b, "PreferredMinThroughput", routing.PreferredMinThroughput)
	writeAnyField(b, "PreferredMaxLatency", routing.PreferredMaxLatency)
	writeAnyField(b, "Sort", routing.Sort)
	b.WriteString("\t\t\t},\n")
}

func writeVercelRoutingField(b *bytes.Buffer, routing *modeldata.VercelAIGatewayRoutingPreference) {
	if routing == nil {
		return
	}
	b.WriteString("\t\t\tVercelAIGatewayRouting: &VercelAIGatewayRoutingPreference{\n")
	writeStringSliceField(b, "Order", "", routing.Order)
	writeStringSliceField(b, "Only", "", routing.Only)
	writeStringSliceField(b, "Models", "", routing.Models)
	writeStringField(b, "Caching", "", routing.Caching)
	writeAnyMapField(b, "BYOK", routing.BYOK)
	b.WriteString("\t\t\t},\n")
}

func writeAzureField(b *bytes.Buffer, config *modeldata.AzureOpenAIResponses) {
	if config == nil {
		return
	}
	b.WriteString("\t\tAzureOpenAIResponses: &AzureOpenAIResponsesConfig{\n")
	writeStringField(b, "Endpoint", "", config.Endpoint)
	writeStringField(b, "Deployment", "", config.Deployment)
	writeStringField(b, "APIVersion", "", config.APIVersion)
	writeStringField(b, "APIKeyEnvVar", "", config.APIKeyEnvVar)
	writeStringField(b, "CredentialSource", "", config.CredentialSource)
	b.WriteString("\t\t},\n")
}

func writeCodexField(b *bytes.Buffer, config *modeldata.OpenAICodexResponses) {
	if config == nil {
		return
	}
	b.WriteString("\t\tOpenAICodexResponses: &OpenAICodexResponsesConfig{\n")
	writeStringField(b, "Model", "", config.Model)
	writeBoolField(b, "SupportsToolSearch", config.SupportsToolSearch)
	b.WriteString("\t\t},\n")
}

func writeProviderMetadataField(b *bytes.Buffer, metadata map[string]any) {
	if len(metadata) == 0 {
		return
	}
	writeAnyMapField(b, "ProviderMetadata", metadata)
}

func writeStringField(b *bytes.Buffer, field, typ, value string) {
	if value == "" {
		return
	}
	if typ == "" {
		fmt.Fprintf(b, "\t\t%s: %s,\n", field, strconv.Quote(value))
		return
	}
	fmt.Fprintf(b, "\t\t%s: %s(%s),\n", field, typ, strconv.Quote(value))
}

func writeIntField(b *bytes.Buffer, field string, value int) {
	if value == 0 {
		return
	}
	fmt.Fprintf(b, "\t\t%s: %d,\n", field, value)
}

func writeFloatField(b *bytes.Buffer, field string, value float64) {
	if value == 0 {
		return
	}
	fmt.Fprintf(b, "\t\t%s: %s,\n", field, formatFloat(value))
}

func writeCostTiers(b *bytes.Buffer, tiers []modeldata.CostTier) {
	if len(tiers) == 0 {
		return
	}
	b.WriteString("\t\tCostTiers: []ModelCostTier{\n")
	for _, tier := range tiers {
		b.WriteString("\t\t\t{\n")
		writeIntField(b, "InputTokensAbove", tier.InputTokensAbove)
		writeFloatField(b, "InputCostPerMillion", tier.InputPerMillion)
		writeFloatField(b, "OutputCostPerMillion", tier.OutputPerMillion)
		writeFloatField(b, "CacheReadInputCostPerMillion", tier.CacheReadInputPerMillion)
		writeFloatField(b, "CacheWriteInputCostPerMillion", tier.CacheWriteInputPerMillion)
		b.WriteString("\t\t\t},\n")
	}
	b.WriteString("\t\t},\n")
}

func writeBoolField(b *bytes.Buffer, field string, value bool) {
	if !value {
		return
	}
	fmt.Fprintf(b, "\t\t%s: true,\n", field)
}

func writeBoolPtrField(b *bytes.Buffer, field string, value *bool) {
	if value == nil {
		return
	}
	fmt.Fprintf(b, "\t\t\t\t%s: generatedBoolPtr(%t),\n", field, *value)
}

func writeStringSliceField(b *bytes.Buffer, field, typ string, values []string) {
	if len(values) == 0 {
		return
	}
	if typ == "" {
		fmt.Fprintf(b, "\t\t%s: []string{", field)
	} else {
		fmt.Fprintf(b, "\t\t%s: []%s{", field, typ)
	}
	for i, value := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		if typ == "" {
			b.WriteString(strconv.Quote(value))
		} else {
			fmt.Fprintf(b, "%s(%s)", typ, strconv.Quote(value))
		}
	}
	b.WriteString("},\n")
}

func writeThinkingLevelMapField(b *bytes.Buffer, values map[string]string) {
	if len(values) == 0 {
		return
	}
	b.WriteString("\t\tThinkingLevelMap: map[ThinkingLevel]string{\n")
	for _, key := range sortedMapKeys(values) {
		fmt.Fprintf(b, "\t\t\tThinkingLevel(%s): %s,\n", strconv.Quote(key), strconv.Quote(values[key]))
	}
	b.WriteString("\t\t},\n")
}

func writeAnyMapField(b *bytes.Buffer, field string, values map[string]any) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "\t\t%s: map[string]any{\n", field)
	for _, key := range sortedAnyMapKeys(values) {
		fmt.Fprintf(b, "\t\t\t%s: ", mapKey(key))
		if key == "apiKeyEnvVars" {
			if values, ok := values[key].([]string); ok {
				writeAPIKeyEnvVarsValue(b, values)
				b.WriteString(",\n")
				continue
			}
		}
		writeAny(b, values[key])
		b.WriteString(",\n")
	}
	b.WriteString("\t\t},\n")
}

func writeAnyField(b *bytes.Buffer, field string, value any) {
	if value == nil {
		return
	}
	fmt.Fprintf(b, "\t\t\t\t%s: ", field)
	writeAny(b, value)
	b.WriteString(",\n")
}

func writeAny(b *bytes.Buffer, value any) {
	switch v := value.(type) {
	case nil:
		b.WriteString("nil")
	case string:
		b.WriteString(strconv.Quote(v))
	case bool:
		fmt.Fprintf(b, "%t", v)
	case float64:
		b.WriteString(formatFloat(v))
	case []string:
		writeStringSliceValue(b, v)
	case []any:
		if strings, ok := stringSliceValue(v); ok {
			writeStringSliceValue(b, strings)
			return
		}
		b.WriteString("[]any{")
		for i, item := range v {
			if i > 0 {
				b.WriteString(", ")
			}
			writeAny(b, item)
		}
		b.WriteString("}")
	case map[string]string:
		writeStringMapValue(b, v)
	case map[string]float64:
		writeFloatMapValue(b, v)
	case map[string]any:
		writeAnyMapValue(b, v)
	default:
		panic(fmt.Sprintf("unsupported metadata value %T", value))
	}
}

func stringSliceValue(values []any) ([]string, bool) {
	strings := make([]string, len(values))
	for i, value := range values {
		stringValue, ok := value.(string)
		if !ok {
			return nil, false
		}
		strings[i] = stringValue
	}
	return strings, true
}

func writeStringSliceValue(b *bytes.Buffer, values []string) {
	b.WriteString("[]string{")
	for i, value := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(value))
	}
	b.WriteString("}")
}

func writeStringMapValue(b *bytes.Buffer, values map[string]string) {
	b.WriteString("map[string]string{")
	keys := sortedMapKeys(values)
	for i, key := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%s: %s", mapKey(key), strconv.Quote(values[key]))
	}
	b.WriteString("}")
}

func writeFloatMapValue(b *bytes.Buffer, values map[string]float64) {
	b.WriteString("map[string]float64{")
	keys := sortedMapKeys(values)
	for i, key := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%s: %s", mapKey(key), formatFloat(values[key]))
	}
	b.WriteString("}")
}

func writeAnyMapValue(b *bytes.Buffer, values map[string]any) {
	b.WriteString("map[string]any{")
	keys := sortedAnyMapKeys(values)
	for i, key := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%s: ", mapKey(key))
		if key == "apiKeyEnvVars" {
			if values, ok := values[key].([]string); ok {
				writeAPIKeyEnvVarsValue(b, values)
				continue
			}
		}
		writeAny(b, values[key])
	}
	b.WriteString("}")
}

func writeAPIKeyEnvVarsValue(b *bytes.Buffer, values []string) {
	b.WriteString("[]string{")
	for i, value := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		if value == "AI_GATEWAY_API_KEY" {
			b.WriteString("defaultVercelAIGatewayKeyEnv")
			continue
		}
		b.WriteString(strconv.Quote(value))
	}
	b.WriteString("}")
}

func writeGoFile(path string, source []byte) error {
	formatted, err := format.Source(source)
	if err != nil {
		return fmt.Errorf("format generated source: %w\n%s", err, source)
	}
	return os.WriteFile(path, formatted, 0o644) // #nosec G306 -- generated Go source is checked in and reviewed.
}

func cloneAnyMap(values map[string]any) map[string]any {
	out := make(map[string]any, len(values))
	for key, value := range values {
		out[key] = value
	}
	return out
}

func cloneStringMap(values map[string]string) map[string]string {
	out := make(map[string]string, len(values))
	for key, value := range values {
		out[key] = value
	}
	return out
}

func cloneFloatMap(values map[string]float64) map[string]float64 {
	out := make(map[string]float64, len(values))
	for key, value := range values {
		out[key] = value
	}
	return out
}

func sortedMapKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedAnyMapKeys(values map[string]any) []string {
	return sortedMapKeys(values)
}

func mapKey(key string) string {
	if key == "apiKeyEnvVars" {
		return "MetadataAPIKeyEnvVars"
	}
	return strconv.Quote(key)
}

func formatFloat(value float64) string {
	return strconv.FormatFloat(value, 'g', -1, 64)
}
