// Copyright (c) 2026 Matthew Winter
//
// This source code is licensed under the MIT license found in the LICENSE file
// in the root directory of this source tree.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/wintermi/sigma/internal/modeldata"
)

const generatedHeader = `// Copyright (c) 2026 Matthew Winter
//
// This source code is licensed under the MIT license found in the LICENSE file
// in the root directory of this source tree.

// Code generated by go generate; DO NOT EDIT.

`

func main() {
	var inputPath string
	var modelsPath string
	var imageModelsPath string

	flag.StringVar(&inputPath, "input", "internal/modeldata/catalog.json", "model metadata catalog JSON")
	flag.StringVar(&modelsPath, "models", "models_generated.go", "generated text model Go file")
	flag.StringVar(&imageModelsPath, "image-models", "image_models_generated.go", "generated image model Go file")
	flag.Parse()

	catalog, err := modeldata.Load(inputPath)
	if err != nil {
		fatalf("load catalog: %v", err)
	}
	if err := writeGoFile(modelsPath, renderTextModels(catalog)); err != nil {
		fatalf("write text models: %v", err)
	}
	if err := writeGoFile(imageModelsPath, renderImageModels(catalog)); err != nil {
		fatalf("write image models: %v", err)
	}
}

func renderTextModels(catalog modeldata.Catalog) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	writeSnapshotComment(&b, catalog)
	b.WriteString("package sigma\n\n")
	b.WriteString("var builtinTextModels = []Model{\n")
	for _, model := range catalog.TextModels {
		writeTextModel(&b, model)
	}
	b.WriteString("}\n\n")
	b.WriteString("func registerBuiltinTextModels(registry *Registry) error {\n")
	b.WriteString("\tfor _, model := range builtinTextModels {\n")
	b.WriteString("\t\tif err := registry.RegisterModel(model, WithMetadataOnly()); err != nil {\n")
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func generatedBoolPtr(value bool) *bool {\n")
	b.WriteString("\treturn &value\n")
	b.WriteString("}\n")
	return b.Bytes()
}

func renderImageModels(catalog modeldata.Catalog) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	writeSnapshotComment(&b, catalog)
	b.WriteString("package sigma\n\n")
	b.WriteString("var builtinImageModels = []ImageModel{\n")
	for _, model := range catalog.ImageModels {
		writeImageModel(&b, model)
	}
	b.WriteString("}\n\n")
	b.WriteString("func registerBuiltinImageModels(registry *Registry) error {\n")
	b.WriteString("\tfor _, model := range builtinImageModels {\n")
	b.WriteString("\t\tif err := registry.RegisterImageModel(model, WithMetadataOnly()); err != nil {\n")
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")
	return b.Bytes()
}

func writeSnapshotComment(b *bytes.Buffer, catalog modeldata.Catalog) {
	fmt.Fprintf(b, "// Source snapshot date: %s.\n", catalog.SnapshotDate)
	b.WriteString("// Source URLs:\n")
	for _, source := range catalog.Sources {
		fmt.Fprintf(b, "// - %s: %s\n", source.Name, source.URL)
	}
	b.WriteByte('\n')
}

func writeTextModel(b *bytes.Buffer, model modeldata.TextModel) {
	b.WriteString("\t{\n")
	writeStringField(b, "ID", "ModelID", model.ID)
	writeStringField(b, "Provider", "ProviderID", model.Provider)
	writeStringField(b, "API", "API", model.API)
	writeStringField(b, "Name", "", model.Name)
	writeIntField(b, "ContextWindow", model.ContextWindow)
	writeIntField(b, "MaxOutputTokens", model.MaxOutputTokens)
	writeStringSliceField(b, "SupportedInputs", "ContentBlockType", model.SupportedInputs)
	writeBoolField(b, "SupportsTools", model.SupportsTools)
	writeBoolField(b, "SupportsThinking", model.SupportsThinking)
	writeStringSliceField(b, "ThinkingLevels", "ThinkingLevel", model.ThinkingLevels)
	writeThinkingLevelMapField(b, model.ThinkingLevelMap)
	writeFloatField(b, "InputCostPerMillion", model.Cost.InputPerMillion)
	writeFloatField(b, "OutputCostPerMillion", model.Cost.OutputPerMillion)
	writeFloatField(b, "CacheReadInputCostPerMillion", model.Cost.CacheReadInputPerMillion)
	writeFloatField(b, "CacheWriteInputCostPerMillion", model.Cost.CacheWriteInputPerMillion)
	writeStringField(b, "CostCurrency", "", model.Cost.Currency)
	writeStringField(b, "DefaultTransport", "Transport", model.DefaultTransport)
	writeOpenAICompatField(b, model.OpenAICompletionsCompat)
	writeAzureField(b, model.AzureOpenAIResponses)
	writeCodexField(b, model.OpenAICodexResponses)
	writeProviderMetadataField(b, textProviderMetadata(model))
	b.WriteString("\t},\n")
}

func writeImageModel(b *bytes.Buffer, model modeldata.ImageModel) {
	b.WriteString("\t{\n")
	writeStringField(b, "ID", "ModelID", model.ID)
	writeStringField(b, "Provider", "ProviderID", model.Provider)
	writeStringField(b, "API", "ImageAPI", model.API)
	writeStringField(b, "Name", "", model.Name)
	writeIntField(b, "MaxWidth", model.MaxWidth)
	writeIntField(b, "MaxHeight", model.MaxHeight)
	writeStringSliceField(b, "SupportedSizes", "", model.SupportedSizes)
	writeStringSliceField(b, "SupportedFormats", "", model.SupportedFormats)
	writeProviderMetadataField(b, imageProviderMetadata(model))
	b.WriteString("\t},\n")
}

func textProviderMetadata(model modeldata.TextModel) map[string]any {
	metadata := cloneAnyMap(model.ProviderMetadata)
	metadata["baseURL"] = model.BaseURL
	metadata["headers"] = cloneStringMap(model.Headers)
	metadata["apiKeyEnvVars"] = append([]string(nil), model.AuthEnvNames...)
	return metadata
}

func imageProviderMetadata(model modeldata.ImageModel) map[string]any {
	metadata := cloneAnyMap(model.ProviderMetadata)
	metadata["baseURL"] = model.BaseURL
	metadata["headers"] = cloneStringMap(model.Headers)
	metadata["apiKeyEnvVars"] = append([]string(nil), model.AuthEnvNames...)
	metadata["cost"] = map[string]any{
		"unit":     model.Cost.Unit,
		"currency": model.Cost.Currency,
		"values":   cloneFloatMap(model.Cost.Values),
	}
	return metadata
}

func writeOpenAICompatField(b *bytes.Buffer, compat *modeldata.OpenAICompletionsCompat) {
	if compat == nil {
		return
	}
	b.WriteString("\t\tOpenAICompletionsCompat: &OpenAICompletionsCompat{\n")
	writeStringField(b, "SupportsStore", "OpenAICompatSupport", compat.SupportsStore)
	writeStringField(b, "SupportsDeveloperRole", "OpenAICompatSupport", compat.SupportsDeveloperRole)
	writeStringField(b, "ReasoningFormat", "OpenAICompletionsReasoningFormat", compat.ReasoningFormat)
	writeStringField(b, "SupportsStreamingUsage", "OpenAICompatSupport", compat.SupportsStreamingUsage)
	writeStringField(b, "SupportsStrictTools", "OpenAICompatSupport", compat.SupportsStrictTools)
	writeStringField(b, "SupportsToolStream", "OpenAICompatSupport", compat.SupportsToolStream)
	writeStringField(b, "MaxTokensField", "OpenAICompletionsMaxTokensField", compat.MaxTokensField)
	writeStringField(b, "CacheControlFormat", "OpenAICompletionsCacheControlFormat", compat.CacheControlFormat)
	writeStringField(b, "SupportsSessionAffinity", "OpenAICompatSupport", compat.SupportsSessionAffinity)
	writeStringField(b, "RequiresToolResultName", "OpenAICompatSupport", compat.RequiresToolResultName)
	writeStringField(b, "RequiresAssistantAfterToolResult", "OpenAICompatSupport", compat.RequiresAssistantAfterToolResult)
	writeStringField(b, "RequiresReasoningContentOnAssistantMessages", "OpenAICompatSupport", compat.RequiresReasoningContentOnAssistantMessages)
	writeOpenRouterRoutingField(b, compat.OpenRouterRouting)
	writeVercelRoutingField(b, compat.VercelAIGatewayRouting)
	b.WriteString("\t\t},\n")
}

func writeOpenRouterRoutingField(b *bytes.Buffer, routing *modeldata.OpenRouterRoutingPreference) {
	if routing == nil {
		return
	}
	b.WriteString("\t\t\tOpenRouterRouting: &OpenRouterRoutingPreference{\n")
	writeStringSliceField(b, "Order", "", routing.Order)
	writeStringSliceField(b, "Only", "", routing.Only)
	writeStringSliceField(b, "Ignore", "", routing.Ignore)
	writeBoolPtrField(b, "AllowFallbacks", routing.AllowFallbacks)
	writeBoolPtrField(b, "RequireParameters", routing.RequireParameters)
	writeStringField(b, "DataCollection", "", routing.DataCollection)
	writeBoolPtrField(b, "ZDR", routing.ZDR)
	writeBoolPtrField(b, "EnforceDistillableText", routing.EnforceDistillableText)
	writeStringField(b, "Sort", "", routing.Sort)
	b.WriteString("\t\t\t},\n")
}

func writeVercelRoutingField(b *bytes.Buffer, routing *modeldata.VercelAIGatewayRoutingPreference) {
	if routing == nil {
		return
	}
	b.WriteString("\t\t\tVercelAIGatewayRouting: &VercelAIGatewayRoutingPreference{\n")
	writeStringSliceField(b, "Order", "", routing.Order)
	writeStringSliceField(b, "Only", "", routing.Only)
	writeStringSliceField(b, "Models", "", routing.Models)
	writeStringField(b, "Caching", "", routing.Caching)
	writeAnyMapField(b, "BYOK", routing.BYOK)
	b.WriteString("\t\t\t},\n")
}

func writeAzureField(b *bytes.Buffer, config *modeldata.AzureOpenAIResponses) {
	if config == nil {
		return
	}
	b.WriteString("\t\tAzureOpenAIResponses: &AzureOpenAIResponsesConfig{\n")
	writeStringField(b, "Endpoint", "", config.Endpoint)
	writeStringField(b, "Deployment", "", config.Deployment)
	writeStringField(b, "APIVersion", "", config.APIVersion)
	writeStringField(b, "APIKeyEnvVar", "", config.APIKeyEnvVar)
	writeStringField(b, "CredentialSource", "", config.CredentialSource)
	b.WriteString("\t\t},\n")
}

func writeCodexField(b *bytes.Buffer, config *modeldata.OpenAICodexResponses) {
	if config == nil {
		return
	}
	b.WriteString("\t\tOpenAICodexResponses: &OpenAICodexResponsesConfig{\n")
	writeStringField(b, "Model", "", config.Model)
	b.WriteString("\t\t},\n")
}

func writeProviderMetadataField(b *bytes.Buffer, metadata map[string]any) {
	if len(metadata) == 0 {
		return
	}
	writeAnyMapField(b, "ProviderMetadata", metadata)
}

func writeStringField(b *bytes.Buffer, field, typ, value string) {
	if value == "" {
		return
	}
	if typ == "" {
		fmt.Fprintf(b, "\t\t%s: %s,\n", field, strconv.Quote(value))
		return
	}
	fmt.Fprintf(b, "\t\t%s: %s(%s),\n", field, typ, strconv.Quote(value))
}

func writeIntField(b *bytes.Buffer, field string, value int) {
	if value == 0 {
		return
	}
	fmt.Fprintf(b, "\t\t%s: %d,\n", field, value)
}

func writeFloatField(b *bytes.Buffer, field string, value float64) {
	if value == 0 {
		return
	}
	fmt.Fprintf(b, "\t\t%s: %s,\n", field, formatFloat(value))
}

func writeBoolField(b *bytes.Buffer, field string, value bool) {
	if !value {
		return
	}
	fmt.Fprintf(b, "\t\t%s: true,\n", field)
}

func writeBoolPtrField(b *bytes.Buffer, field string, value *bool) {
	if value == nil {
		return
	}
	fmt.Fprintf(b, "\t\t\t\t%s: generatedBoolPtr(%t),\n", field, *value)
}

func writeStringSliceField(b *bytes.Buffer, field, typ string, values []string) {
	if len(values) == 0 {
		return
	}
	if typ == "" {
		fmt.Fprintf(b, "\t\t%s: []string{", field)
	} else {
		fmt.Fprintf(b, "\t\t%s: []%s{", field, typ)
	}
	for i, value := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		if typ == "" {
			b.WriteString(strconv.Quote(value))
		} else {
			fmt.Fprintf(b, "%s(%s)", typ, strconv.Quote(value))
		}
	}
	b.WriteString("},\n")
}

func writeThinkingLevelMapField(b *bytes.Buffer, values map[string]string) {
	if len(values) == 0 {
		return
	}
	b.WriteString("\t\tThinkingLevelMap: map[ThinkingLevel]string{\n")
	for _, key := range sortedMapKeys(values) {
		fmt.Fprintf(b, "\t\t\tThinkingLevel(%s): %s,\n", strconv.Quote(key), strconv.Quote(values[key]))
	}
	b.WriteString("\t\t},\n")
}

func writeAnyMapField(b *bytes.Buffer, field string, values map[string]any) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "\t\t%s: map[string]any{\n", field)
	for _, key := range sortedAnyMapKeys(values) {
		fmt.Fprintf(b, "\t\t\t%s: ", mapKey(key))
		writeAny(b, values[key])
		b.WriteString(",\n")
	}
	b.WriteString("\t\t},\n")
}

func writeAny(b *bytes.Buffer, value any) {
	switch v := value.(type) {
	case nil:
		b.WriteString("nil")
	case string:
		b.WriteString(strconv.Quote(v))
	case bool:
		fmt.Fprintf(b, "%t", v)
	case float64:
		b.WriteString(formatFloat(v))
	case []string:
		writeStringSliceValue(b, v)
	case []any:
		b.WriteString("[]any{")
		for i, item := range v {
			if i > 0 {
				b.WriteString(", ")
			}
			writeAny(b, item)
		}
		b.WriteString("}")
	case map[string]string:
		writeStringMapValue(b, v)
	case map[string]float64:
		writeFloatMapValue(b, v)
	case map[string]any:
		writeAnyMapValue(b, v)
	default:
		panic(fmt.Sprintf("unsupported metadata value %T", value))
	}
}

func writeStringSliceValue(b *bytes.Buffer, values []string) {
	b.WriteString("[]string{")
	for i, value := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(value))
	}
	b.WriteString("}")
}

func writeStringMapValue(b *bytes.Buffer, values map[string]string) {
	b.WriteString("map[string]string{")
	keys := sortedMapKeys(values)
	for i, key := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%s: %s", mapKey(key), strconv.Quote(values[key]))
	}
	b.WriteString("}")
}

func writeFloatMapValue(b *bytes.Buffer, values map[string]float64) {
	b.WriteString("map[string]float64{")
	keys := sortedMapKeys(values)
	for i, key := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%s: %s", mapKey(key), formatFloat(values[key]))
	}
	b.WriteString("}")
}

func writeAnyMapValue(b *bytes.Buffer, values map[string]any) {
	b.WriteString("map[string]any{")
	keys := sortedAnyMapKeys(values)
	for i, key := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%s: ", mapKey(key))
		writeAny(b, values[key])
	}
	b.WriteString("}")
}

func writeGoFile(path string, source []byte) error {
	formatted, err := format.Source(source)
	if err != nil {
		return fmt.Errorf("format generated source: %w\n%s", err, source)
	}
	return os.WriteFile(path, formatted, 0o644) //nolint:gosec
}

func cloneAnyMap(values map[string]any) map[string]any {
	out := make(map[string]any, len(values))
	for key, value := range values {
		out[key] = value
	}
	return out
}

func cloneStringMap(values map[string]string) map[string]string {
	out := make(map[string]string, len(values))
	for key, value := range values {
		out[key] = value
	}
	return out
}

func cloneFloatMap(values map[string]float64) map[string]float64 {
	out := make(map[string]float64, len(values))
	for key, value := range values {
		out[key] = value
	}
	return out
}

func sortedMapKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedAnyMapKeys(values map[string]any) []string {
	return sortedMapKeys(values)
}

func mapKey(key string) string {
	if key == "apiKeyEnvVars" {
		return "MetadataAPIKeyEnvVars"
	}
	return strconv.Quote(key)
}

func formatFloat(value float64) string {
	return strconv.FormatFloat(value, 'g', -1, 64)
}

func fatalf(format string, args ...any) {
	message := strings.TrimSuffix(fmt.Sprintf(format, args...), "\n")
	fmt.Fprintln(os.Stderr, "sigma-generate-models: "+message)
	os.Exit(1)
}
